# Generated by Django 5.2.8 on 2026-03-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badgeuser', '0030_badgeuser_zip_code_squashed_0031_alter_badgeuser_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgeuser',
            name='quota_release_informed',
            field=models.BooleanField(default=False),
        ),
    ]
