# Generated by Django 5.2.8 on 2025-12-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0047_rename_badgeinstance_recipient_identifier_badgeclass_revoked_issuer_badg_recipie_6a2cd8_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgeclass',
            name='course_url',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
