# Generated by Django 5.2.8 on 2025-12-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0049_badgeinstance_course_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='course_url',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
