# Generated by Django 5.2.8 on 2025-12-09 13:53

import jsonfield.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("issuer", "0050_qrcode_course_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="qrcode",
            name="evidence_items",
            field=jsonfield.fields.JSONField(blank=True, default=list),
        ),
    ]
