# Generated by Django 5.2.8 on 2026-01-23 16:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0051_qrcode_evidence_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuer',
            name='quota_accounts_admin',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Admin Accounts'),
        ),
        migrations.AddField(
            model_name='issuer',
            name='quota_accounts_member',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Member Accounts'),
        ),
        migrations.AddField(
            model_name='issuer',
            name='quota_aiskills_requests',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='AI Tool Requests'),
        ),
        migrations.AddField(
            model_name='issuer',
            name='quota_badge_award',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Award Badges'),
        ),
        migrations.AddField(
            model_name='issuer',
            name='quota_badge_create',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Create Badges'),
        ),
        migrations.AddField(
            model_name='issuer',
            name='quota_learningpath_create',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Create Learningpaths'),
        ),
        migrations.AddField(
            model_name='issuer',
            name='quota_pdfeditor',
            field=models.BooleanField(blank=True, null=True, verbose_name='PDF Editor'),
        ),
        migrations.AddField(
            model_name='issuer',
            name='quota_period_start',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Period start'),
        ),
        migrations.CreateModel(
            name='Quota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('price', models.FloatField(blank=True, null=True)),
                ('default', models.BooleanField(default=False)),
                ('badge_create', models.PositiveIntegerField(verbose_name='Create Badges')),
                ('badge_award', models.PositiveIntegerField(verbose_name='Award Badges')),
                ('learningpath_create', models.PositiveIntegerField(verbose_name='Create Learningpaths')),
                ('accounts_admin', models.PositiveIntegerField(verbose_name='Admin Accounts')),
                ('accounts_member', models.PositiveIntegerField(verbose_name='Member Accounts')),
                ('aiskills_requests', models.PositiveIntegerField(verbose_name='AI Tool Requests')),
                ('pdfeditor', models.BooleanField(verbose_name='PDF Editor')),
                ('upgrade', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='issuer.quota')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='issuer',
            name='quota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='issuer.quota'),
        ),
    ]
