# Generated by Django 3.2 on 2025-11-21 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("issuer", "0051_qrcode_evidence_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningpath",
            name="archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="learningpath",
            name="archived_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
