# Generated by Django 5.2.8 on 2026-03-18 09:09

import django.db.migrations.operations.special
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def populate_key(apps, schema_editor):
    quotas = apps.get_model('issuer', 'Quota')
    for quota in quotas.objects.all().iterator():
        quota.key = quota.name.upper()
        quota.save()

class Migration(migrations.Migration):

    replaces = [('issuer', '0052_issuer_quota_accounts_admin_and_more'), ('issuer', '0053_aiskillrequest'), ('issuer', '0054_alter_quota_default'), ('issuer', '0055_issuer_quota_network_memberships_and_more'), ('issuer', '0056_quotarequest_individualquotarequest_and_more'), ('issuer', '0057_quota_key'), ('issuer', '0058_issuer_quota_network_create_and_more'), ('issuer', '0059_alter_quota_upgrade'), ('issuer', '0060_remove_quotarequest_issuer_and_more')]

    dependencies = [
        ('issuer', '0051_qrcode_evidence_items'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='issuer',
            name='quota_accounts_admin',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Admin Accounts'),
        ),
        migrations.AddField(
            model_name='issuer',
            name='quota_accounts_member',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Member Accounts'),
        ),
        migrations.AddField(
            model_name='issuer',
            name='quota_aiskills_requests',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='AI Tool Requests'),
        ),
        migrations.AddField(
            model_name='issuer',
            name='quota_badge_award',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Award Badges'),
        ),
        migrations.AddField(
            model_name='issuer',
            name='quota_badge_create',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Create Badges'),
        ),
        migrations.AddField(
            model_name='issuer',
            name='quota_learningpath_create',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Create Learningpaths'),
        ),
        migrations.AddField(
            model_name='issuer',
            name='quota_pdfeditor',
            field=models.BooleanField(blank=True, null=True, verbose_name='PDF Editor'),
        ),
        migrations.AddField(
            model_name='issuer',
            name='quota_period_start',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Period start'),
        ),
        migrations.CreateModel(
            name='Quota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('price', models.FloatField(blank=True, null=True)),
                ('default', models.CharField(choices=[('NONE', 'None'), ('ISSUER', 'Issuer'), ('NETWORK', 'Network')], default='NONE', max_length=254)),
                ('badge_create', models.PositiveIntegerField(verbose_name='Create Badges')),
                ('badge_award', models.PositiveIntegerField(verbose_name='Award Badges')),
                ('learningpath_create', models.PositiveIntegerField(verbose_name='Create Learningpaths')),
                ('accounts_admin', models.PositiveIntegerField(verbose_name='Admin Accounts')),
                ('accounts_member', models.PositiveIntegerField(verbose_name='Member Accounts')),
                ('aiskills_requests', models.PositiveIntegerField(verbose_name='AI Tool Requests')),
                ('pdfeditor', models.BooleanField(verbose_name='PDF Editor')),
                ('upgrade', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='issuer.quota')),
                ('network_memberships', models.PositiveIntegerField(default=0, verbose_name='Network Memberships')),
                ('key', models.CharField(max_length=254, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='issuer',
            name='quota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='issuer.quota'),
        ),
        migrations.CreateModel(
            name='AiSkillRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aiskill_requests', to='issuer.issuer')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='issuer',
            name='quota_network_memberships',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Network Memberships'),
        ),
        migrations.CreateModel(
            name='QuotaRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=254)),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quota_requests', to='issuer.issuer')),
            ],
        ),
        migrations.CreateModel(
            name='IndividualQuotaRequest',
            fields=[
                ('quotarequest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='issuer.quotarequest')),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Quotas: Individual Requests',
            },
            bases=('issuer.quotarequest',),
        ),
        migrations.CreateModel(
            name='UpgradeQuotaRequest',
            fields=[
                ('quotarequest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='issuer.quotarequest')),
                ('package', models.CharField(choices=[('FREE', 'Free'), ('PRO', 'Pro'), ('ENTERPRISE', 'Enterprise'), ('NETWORK', 'Network')], max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Quotas: Upgrade Requests',
            },
            bases=('issuer.quotarequest',),
        ),
        migrations.RunPython(
            code=populate_key,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='quota',
            name='key',
            field=models.CharField(max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='issuer',
            name='quota_network_create',
            field=models.BooleanField(blank=True, null=True, verbose_name='Create Networks'),
        ),
        migrations.AlterField(
            model_name='quota',
            name='upgrade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='issuer.quota'),
        ),
        migrations.AlterField(
            model_name='learningpath',
            name='participationBadge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learningpath_as_participationbadge', to='issuer.badgeclass'),
        ),
        migrations.CreateModel(
            name='QuotaUpgradeRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=254)),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quota_requests', to='issuer.issuer')),
                ('quota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='issuer.quota')),
            ],
            options={
                'verbose_name_plural': 'Quotas: Upgrade Requests',
            },
        ),
        migrations.DeleteModel(
            name='IndividualQuotaRequest',
        ),
        migrations.DeleteModel(
            name='QuotaRequest',
        ),
        migrations.DeleteModel(
            name='UpgradeQuotaRequest',
        ),
    ]
