# Generated by Django 5.2.8 on 2026-03-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0051_qrcode_evidence_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgeclass',
            name='language',
            field=models.CharField(blank=True, default=None, max_length=2, null=True),
        ),
    ]
