# Generated by Django 5.2.8 on 2026-02-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0053_aiskillrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quota',
            name='default',
            field=models.CharField(choices=[('NONE', 'None'), ('ISSUER', 'Issuer'), ('NETWORK', 'Network')], default='NONE', max_length=254),
        ),
    ]
