# Generated by Django 5.2.8 on 2026-02-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0054_alter_quota_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuer',
            name='quota_network_memberships',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Network Memberships'),
        ),
        migrations.AddField(
            model_name='quota',
            name='network_memberships',
            field=models.PositiveIntegerField(default=0, verbose_name='Network Memberships'),
            preserve_default=False,
        ),
    ]
