# Generated by Django 5.2.8 on 2026-02-18 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0055_issuer_quota_network_memberships_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotaRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=254)),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quota_requests', to='issuer.issuer')),
            ],
        ),
        migrations.CreateModel(
            name='IndividualQuotaRequest',
            fields=[
                ('quotarequest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='issuer.quotarequest')),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Quotas: Individual Requests',
            },
            bases=('issuer.quotarequest',),
        ),
        migrations.CreateModel(
            name='UpgradeQuotaRequest',
            fields=[
                ('quotarequest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='issuer.quotarequest')),
                ('package', models.CharField(choices=[('FREE', 'Free'), ('PRO', 'Pro'), ('ENTERPRISE', 'Enterprise'), ('NETWORK', 'Network')], max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Quotas: Upgrade Requests',
            },
            bases=('issuer.quotarequest',),
        ),
    ]
