# Generated by Django 5.2.8 on 2026-03-06 09:48

from django.db import migrations, models


def populate_key(apps, schema_editor):
    quotas = apps.get_model('issuer', 'Quota')
    for quota in quotas.objects.all().iterator():
        quota.key = quota.name.upper()
        quota.save()

class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0056_quotarequest_individualquotarequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quota',
            name='key',
            field=models.CharField(max_length=254, null=True),
            preserve_default=False,
        ),
        migrations.RunPython(populate_key, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='quota',
            name='key',
            field=models.CharField(max_length=254, unique=True),
        ),
    ]
