# Generated by Django 5.2.8 on 2026-03-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0057_quota_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuer',
            name='quota_network_create',
            field=models.BooleanField(blank=True, null=True, verbose_name='Create Networks'),
        ),
    ]
