# Generated by Django 5.2.8 on 2026-03-11 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0058_issuer_quota_network_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quota',
            name='upgrade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='issuer.quota'),
        ),
    ]
