# Generated by Django 5.2.8 on 2026-03-13 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0059_alter_quota_upgrade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningpath',
            name='participationBadge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learningpath_as_participationbadge', to='issuer.badgeclass'),
        ),
        migrations.CreateModel(
            name='QuotaUpgradeRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=254)),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quota_requests', to='issuer.issuer')),
                ('quota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='issuer.quota')),
            ],
            options={
                'verbose_name_plural': 'Quotas: Upgrade Requests',
            },
        ),
        migrations.DeleteModel(
            name='IndividualQuotaRequest',
        ),
        migrations.DeleteModel(
            name='QuotaRequest',
        ),
        migrations.DeleteModel(
            name='UpgradeQuotaRequest',
        ),
    ]
