# Generated by Django 5.2.8 on 2026-03-17 12:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0060_remove_quotarequest_issuer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuer',
            name='quota_network_period_start',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Period start'),
        ),
    ]
