# Generated by Django 5.2.8 on 2026-03-20 08:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0061_issuer_quota_network_period_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuer',
            name='quota_network_period_start',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Network period start'),
        ),
        migrations.AlterField(
            model_name='quota',
            name='network_memberships',
            field=models.PositiveIntegerField(verbose_name='Network Memberships'),
        ),
        migrations.AlterField(
            model_name='quota',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
    ]
