# Generated by Django 5.2.8 on 2026-03-26 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0052_auto_20251121_2108'),
        ('issuer', '0062_alter_issuer_quota_network_period_start_and_more'),
    ]

    operations = [
    ]
