# Generated by Django 5.2.8 on 2026-03-28 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0063_merge_all_0052_heads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badgeclass',
            name='language',
            field=models.CharField(blank=True, default='en', max_length=2, null=True),
        ),
        migrations.CreateModel(
            name='BadgeClassArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=254)),
                ('badgeclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issuer.badgeclass')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
