# Generated by Django 5.2.8 on 2026-03-26 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0063_merge_20260326_0945'),
        ('issuer', '0063_merge_20260326_1013'),
    ]

    operations = [
    ]
