# Generated by Django 5.2.8 on 2026-04-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0063_merge_all_0052_heads'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuer',
            name='quota_dashboard',
            field=models.BooleanField(blank=True, null=True, verbose_name='Dashboard'),
        ),
        migrations.AddField(
            model_name='quota',
            name='dashboard',
            field=models.BooleanField(default=False, verbose_name='Dashboard'),
            preserve_default=False,
        ),
    ]
