# Generated by Django 5.2.8 on 2026-08-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0082_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badgeclass',
            name='language',
            field=models.CharField(blank=True, default='en', max_length=2, null=True),
        ),
    ]
