# Generated by Django 5.2.8 on 2026-08-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0083_alter_badgeclass_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='auto_issuance',
            field=models.BooleanField(default=False),
        ),
    ]
