from django.urls import re_path

from issuer.api import (
    BadgeClassNetworkShareView,
    BadgeRequestList,
    IssuerAwardableBadgeClassList,
    IssuerLearningPathList,
    IssuerList,
    IssuerNetworkBadgeClassList,
    IssuerSharedNetworkBadgesView,
    IssuerStaffRequestConfirm,
    NetworkBadgeClassesList,
    NetworkBadgeInstanceList,
    NetworkBadgeQRCodeList,
    NetworkDetail,
    NetworkInvitation,
    NetworkInvitationConfirm,
    NetworkInvitationList,
    NetworkIssuerDetail,
    NetworkList,
    IssuerDetail,
    IssuerBadgeClassList,
    BadgeClassDetail,
    BadgeInstanceList,
    BadgeInstanceDetail,
    IssuerBadgeInstanceList,
    AllBadgeClassesList,
    BatchAssertionsIssue,
    IssuerStaffRequestDetail,
    IssuerStaffRequestList,
    LearningPathDetail,
    LearningPathParticipantsList,
    NetworkSharedBadgesView,
    NetworkUserIssuersList,
    QRCodeDetail,
    BadgeImageComposition,
    QRCodeList,
)
from issuer.api_v1 import FindBadgeClassDetail, IssuerStaffList
from dashboard.network_api import (
    NetworkDashboardKPIsView,
    NetworkDashboardCompetencyAreasView,
    NetworkDashboardTopBadgesView,
    NetworkDashboardRecentActivityView,
    NetworkDashboardStrengthenedCompetenciesView,
    NetworkDashboardCompetencyDetailView,
    NetworkDashboardCompetencyAreaDetailView,
    NetworkDashboardBadgeAwardsTimelineView,
    NetworkDashboardBadgeTypeDistributionView,
    NetworkDashboardDeliveryMethodDistributionView,
    NetworkDashboardRecentBadgeAwardsView,
    NetworkDashboardBadgeLocationsView,
    NetworkDashboardLearnersOverviewView,
    NetworkDashboardLearnersResidenceView,
    NetworkDashboardLearnersResidenceDetailView,
    NetworkDashboardLearnersGenderView,
    NetworkDashboardLearnersGenderDetailView,
    NetworkDashboardCompetencyAreasSkillsView,
    NetworkDashboardSocialspaceInstitutionsView,
    NetworkDashboardSocialspaceCitiesView,
    NetworkDashboardSocialspaceCityDetailView,
    NetworkDashboardSocialspaceLearnersView,
    NetworkDashboardSocialspaceCompetenciesView,
)

urlpatterns = [
    # url(r'^$', RedirectView.as_view(url='/v1/issuer/issuers', permanent=False)),
    re_path(
        r"^all-badges$",
        AllBadgeClassesList.as_view(),
        name="v1_api_issuer_all_badges_list",
    ),
    re_path(
        r"^all-badges/find$",
        FindBadgeClassDetail.as_view(),
        name="v1_api_find_badgeclass_by_identifier",
    ),
    re_path(r"^issuers$", IssuerList.as_view(), name="v1_api_issuer_list"),
    re_path(
        r"^issuers/(?P<slug>[^/]+)$",
        IssuerDetail.as_view(),
        name="v1_api_issuer_detail",
    ),
    re_path(r"^networks$", NetworkList.as_view(), name="v1_api_network_list"),
    re_path(
        r"^networks/(?P<slug>[^/]+)$",
        NetworkDetail.as_view(),
        name="v1_api_issuer_detail",
    ),
    re_path(
        r"^issuers/(?P<slug>[^/]+)/staff$",
        IssuerStaffList.as_view(),
        name="v1_api_issuer_staff",
    ),
    re_path(
        r"^issuers/(?P<slug>[^/]+)/badges$",
        IssuerBadgeClassList.as_view(),
        name="v1_api_badgeclass_list",
    ),
    re_path(
        r"^networks/(?P<slug>[^/]+)/badges$",
        NetworkBadgeClassesList.as_view(),
        name="v1_api_network_badgeclass_list",
    ),
    re_path(
        r"^issuers/(?P<slug>[^/]+)/awardable-badges$",
        IssuerAwardableBadgeClassList.as_view(),
        name="v1_issuer_awardable_badgeclasses",
    ),
    re_path(
        r"^networks/(?P<networkSlug>[^/]+)/badges/(?P<badgeSlug>[^/]+)/share$",
        BadgeClassNetworkShareView.as_view(),
        name="v1_api_network_badge_share_detail",
    ),
    re_path(
        r"^networks/(?P<entity_id>[^/]+)/shared-badges$",
        NetworkSharedBadgesView.as_view(),
        name="v1_api_network_shared_badges",
    ),
    re_path(
        r"^issuers/(?P<entity_id>[^/]+)/networks/shared-badges$",
        IssuerSharedNetworkBadgesView.as_view(),
        name="v1_api_issuer_shared_network_badges",
    ),
    re_path(
        r"^issuers/(?P<issuerSlug>[^/]+)/badges/(?P<badgeSlug>[^/]+)/qrcodes/(?P<slug>[^/]+)$",
        QRCodeDetail.as_view(),
        name="v1_api_qrcode_detail",
    ),
    re_path(
        r"^issuers/(?P<issuerSlug>[^/]+)/badges/(?P<badgeSlug>[^/]+)/qrcodes$",
        QRCodeList.as_view(),
        name="v1_api_qrcode_list",
    ),
    re_path(
        r"^networks/(?P<networkSlug>[^/]+)/badges/(?P<badgeSlug>[^/]+)/qrcodes$",
        NetworkBadgeQRCodeList.as_view(),
        name="v1_api_network_badge_qrcode_list",
    ),
    re_path(
        r"^networks/(?P<networkSlug>[^/]+)/issuers$",
        NetworkUserIssuersList.as_view(),
        name="v1_api_network_issuer_list",
    ),
    re_path(
        r"^issuers/(?P<issuerSlug>[^/]+)/badges/(?P<badgeSlug>[^/]+)/qrcodes/(?P<slug>[^/]+)$",
        QRCodeDetail.as_view(),
        name="v1_api_qrcode_detail",
    ),
    re_path(
        r"^issuers/(?P<issuerSlug>[^/]+)/badges/(?P<badgeSlug>[^/]+)/requests$",
        BadgeRequestList.as_view(),
        name="v1_api_badgerequest_list",
    ),
    re_path(
        r"^issuers/(?P<issuerSlug>[^/]+)/badges/(?P<slug>[^/]+)$",
        BadgeClassDetail.as_view(),
        name="v1_api_badgeclass_detail",
    ),
    re_path(
        r"^issuers/(?P<issuerSlug>[^/]+)/badges/(?P<slug>[^/]+)/batchAssertions$",
        BatchAssertionsIssue.as_view(),
        name="v1_api_badgeclass_batchissue",
    ),
    re_path(
        r"^issuers/(?P<issuerSlug>[^/]+)/badges/(?P<slug>[^/]+)/batch-assertions/status/(?P<task_id>[^/]+)$",
        BatchAssertionsIssue.as_view(),
        name="batch-assertions-status",
    ),
    re_path(
        r"^issuers/(?P<issuerSlug>[^/]+)/badges/(?P<slug>[^/]+)/assertions$",
        BadgeInstanceList.as_view(),
        name="v1_api_badgeinstance_list",
    ),
    re_path(
        r"^issuers/(?P<issuerSlug>[^/]+)/network/badges$",
        IssuerNetworkBadgeClassList.as_view(),
        name="v1_api_issuer_network_badgeclass_list",
    ),
    re_path(
        r"^issuers/(?P<issuerSlug>[^/]+)/badges/(?P<slug>[^/]+)/network-assertions$",
        NetworkBadgeInstanceList.as_view(),
        name="v1_api_network_badgeinstance_list",
    ),
    re_path(
        r"^issuers/(?P<slug>[^/]+)/assertions$",
        IssuerBadgeInstanceList.as_view(),
        name="v1_api_issuer_instance_list",
    ),
    re_path(
        r"^issuers/(?P<issuerSlug>[^/]+)/badges/(?P<badgeSlug>[^/]+)/assertions/(?P<slug>[^/]+)$",
        BadgeInstanceDetail.as_view(),
        name="v1_api_badgeinstance_detail",
    ),
    re_path(
        r"^issuers/(?P<slug>[^/]+)/learningpath$",
        IssuerLearningPathList.as_view(),
        name="v1_api_learningpath_list",
    ),
    re_path(
        r"^networks/(?P<slug>[^/]+)/issuer/(?P<issuer_slug>[^/]+)$",
        NetworkIssuerDetail.as_view(),
        name="v1_api_network_issuer_detail",
    ),
    re_path(
        r"^issuers/(?P<issuerSlug>[^/]+)/learningpath/(?P<slug>[^/]+)$",
        LearningPathDetail.as_view(),
        name="v1_api_learningpath_detail",
    ),
    re_path(
        r"^learningpath/(?P<slug>[^/]+)/participants$",
        LearningPathParticipantsList.as_view(),
        name="v1_api_learningpath_participant_list",
    ),
    re_path(
        r"^issuers/(?P<issuerSlug>[^/]+)/staffRequests$",
        IssuerStaffRequestList.as_view(),
        name="v1_api_staffrequest_list",
    ),
    re_path(
        r"^issuers/(?P<issuerSlug>[^/]+)/staffRequests/(?P<requestId>[^/]+)$",
        IssuerStaffRequestDetail.as_view(),
        name="v1_api_staffrequest_detail",
    ),
    re_path(
        r"^issuers/(?P<issuerSlug>[^/]+)/staffRequests/(?P<requestId>[^/]+)/confirm$",
        IssuerStaffRequestConfirm.as_view(),
        name="v1_api_staffrequest_confirmation",
    ),
    re_path(
        r"^issuers/(?P<issuerSlug>[^/]+)/badges/image/compose$",
        BadgeImageComposition.as_view(),
        name="v1_api_badge_image_composition",
    ),
    re_path(
        r"^networks/(?P<networkSlug>[^/]+)/invites$",
        NetworkInvitationList.as_view(),
        name="v1_api_network_invite_list",
    ),
    re_path(
        r"^networks/invites/(?P<slug>[^/]+)$",
        NetworkInvitation.as_view(),
        name="v1_api_network_invite_detail",
    ),
    re_path(
        r"^networks/(?P<networkSlug>[^/]+)/invite/(?P<slug>[^/]+)/confirm$",
        NetworkInvitationConfirm.as_view(),
        name="v1_api_network_invite_confirmation",
    ),
    # Network Dashboard endpoints
    re_path(
        r"^networks/(?P<networkSlug>[^/]+)/dashboard/kpis$",
        NetworkDashboardKPIsView.as_view(),
        name="v1_api_network_dashboard_kpis",
    ),
    re_path(
        r"^networks/(?P<networkSlug>[^/]+)/dashboard/competency-areas$",
        NetworkDashboardCompetencyAreasView.as_view(),
        name="v1_api_network_dashboard_competency_areas",
    ),
    re_path(
        r"^networks/(?P<networkSlug>[^/]+)/dashboard/top-badges$",
        NetworkDashboardTopBadgesView.as_view(),
        name="v1_api_network_dashboard_top_badges",
    ),
    re_path(
        r"^networks/(?P<networkSlug>[^/]+)/dashboard/recent-activity$",
        NetworkDashboardRecentActivityView.as_view(),
        name="v1_api_network_dashboard_recent_activity",
    ),
    re_path(
        r"^networks/(?P<networkSlug>[^/]+)/dashboard/strengthened-competencies$",
        NetworkDashboardStrengthenedCompetenciesView.as_view(),
        name="v1_api_network_dashboard_strengthened_competencies",
    ),
    re_path(
        r"^networks/(?P<networkSlug>[^/]+)/dashboard/strengthened-competencies/(?P<competencyId>[^/]+)$",
        NetworkDashboardCompetencyDetailView.as_view(),
        name="v1_api_network_dashboard_competency_detail",
    ),
    re_path(
        r"^networks/(?P<networkSlug>[^/]+)/dashboard/competency-area-detail$",
        NetworkDashboardCompetencyAreaDetailView.as_view(),
        name="v1_api_network_dashboard_competency_area_detail",
    ),
    re_path(
        r"^networks/(?P<networkSlug>[^/]+)/dashboard/badge-awards-timeline$",
        NetworkDashboardBadgeAwardsTimelineView.as_view(),
        name="v1_api_network_dashboard_badge_awards_timeline",
    ),
    re_path(
        r"^networks/(?P<networkSlug>[^/]+)/dashboard/badge-type-distribution$",
        NetworkDashboardBadgeTypeDistributionView.as_view(),
        name="v1_api_network_dashboard_badge_type_distribution",
    ),
    re_path(
        r"^networks/(?P<networkSlug>[^/]+)/dashboard/delivery-method-distribution$",
        NetworkDashboardDeliveryMethodDistributionView.as_view(),
        name="v1_api_network_dashboard_delivery_method_distribution",
    ),
    re_path(
        r"^networks/(?P<networkSlug>[^/]+)/dashboard/recent-badge-awards$",
        NetworkDashboardRecentBadgeAwardsView.as_view(),
        name="v1_api_network_dashboard_recent_badge_awards",
    ),
    re_path(
        r"^networks/(?P<networkSlug>[^/]+)/dashboard/badge-locations$",
        NetworkDashboardBadgeLocationsView.as_view(),
        name="v1_api_network_dashboard_badge_locations",
    ),
    # Network Dashboard - Learners endpoints
    re_path(
        r"^networks/(?P<networkSlug>[^/]+)/dashboard/learners$",
        NetworkDashboardLearnersOverviewView.as_view(),
        name="v1_api_network_dashboard_learners",
    ),
    re_path(
        r"^networks/(?P<networkSlug>[^/]+)/dashboard/learners/residence$",
        NetworkDashboardLearnersResidenceView.as_view(),
        name="v1_api_network_dashboard_learners_residence",
    ),
    re_path(
        r"^networks/(?P<networkSlug>[^/]+)/dashboard/learners/residence/(?P<city>[^/]+)$",
        NetworkDashboardLearnersResidenceDetailView.as_view(),
        name="v1_api_network_dashboard_learners_residence_detail",
    ),
    re_path(
        r"^networks/(?P<networkSlug>[^/]+)/dashboard/learners/gender$",
        NetworkDashboardLearnersGenderView.as_view(),
        name="v1_api_network_dashboard_learners_gender",
    ),
    re_path(
        r"^networks/(?P<networkSlug>[^/]+)/dashboard/learners/gender/(?P<gender>[^/]+)$",
        NetworkDashboardLearnersGenderDetailView.as_view(),
        name="v1_api_network_dashboard_learners_gender_detail",
    ),
    # Network Dashboard - Competency Areas Skills Tree endpoint
    re_path(
        r"^networks/(?P<networkSlug>[^/]+)/dashboard/competency-areas/skills$",
        NetworkDashboardCompetencyAreasSkillsView.as_view(),
        name="v1_api_network_dashboard_competency_areas_skills",
    ),
    # Network Dashboard - Sozialraum/Socialspace endpoints
    re_path(
        r"^networks/(?P<networkSlug>[^/]+)/dashboard/socialspace/institutions$",
        NetworkDashboardSocialspaceInstitutionsView.as_view(),
        name="v1_api_network_dashboard_socialspace_institutions",
    ),
    re_path(
        r"^networks/(?P<networkSlug>[^/]+)/dashboard/socialspace/cities$",
        NetworkDashboardSocialspaceCitiesView.as_view(),
        name="v1_api_network_dashboard_socialspace_cities",
    ),
    re_path(
        r"^networks/(?P<networkSlug>[^/]+)/dashboard/socialspace/city-detail$",
        NetworkDashboardSocialspaceCityDetailView.as_view(),
        name="v1_api_network_dashboard_socialspace_city_detail",
    ),
    re_path(
        r"^networks/(?P<networkSlug>[^/]+)/dashboard/socialspace/learners$",
        NetworkDashboardSocialspaceLearnersView.as_view(),
        name="v1_api_network_dashboard_socialspace_learners",
    ),
    re_path(
        r"^networks/(?P<networkSlug>[^/]+)/dashboard/socialspace/competencies$",
        NetworkDashboardSocialspaceCompetenciesView.as_view(),
        name="v1_api_network_dashboard_socialspace_competencies",
    ),
]
