FROM python:3.10-slim-bookworm

RUN mkdir /badgr_server
WORKDIR /badgr_server

RUN apt-get clean all && apt-get update && apt-get upgrade -y
RUN apt-get install -y default-libmysqlclient-dev \
    python3-dev \
    python3-cairo \
    build-essential \
    xmlsec1 \
    libxmlsec1-dev \
    pkg-config \
    default-mysql-client \
    curl \
    xz-utils

RUN pip install uwsgi

COPY requirements.txt              /badgr_server

COPY entrypoint.dev.sh             /badgr_server

COPY crontab                       /etc/cron.d/crontab

COPY openbadges                    /badgr_server

COPY openbadges_bakery             /badgr_server

RUN chmod +x entrypoint.dev.sh

RUN touch /var/log/cron_cleartokens.log && chmod 644 /var/log/cron_cleartokens.log
RUN touch /var/log/cron_qr_badgerequests.log && chmod 644 /var/log/cron_qr_badgerequests.log
RUN touch /var/log/cron_clear_altcha.log && chmod 644 /var/log/cron_clear_altcha.log
RUN touch /var/log/cron_clear_iframe_urls.log && chmod 644 /var/log/cron_clear_iframe_urls.log

ENV SUPERCRONIC_URL=https://github.com/aptible/supercronic/releases/download/v0.2.30/supercronic-linux-amd64 \
    SUPERCRONIC=supercronic-linux-amd64 \
    SUPERCRONIC_SHA1SUM=9f27ad28c5c57cd133325b2a66bba69ba2235799
ENV TZ="Europe/Berlin"

RUN curl -fsSLO "$SUPERCRONIC_URL" \
    && echo "${SUPERCRONIC_SHA1SUM}  ${SUPERCRONIC}" | sha1sum -c - \
    && chmod +x "$SUPERCRONIC" \
    && mv "$SUPERCRONIC" "/usr/local/bin/${SUPERCRONIC}" \
    && ln -s "/usr/local/bin/${SUPERCRONIC}" /usr/local/bin/supercronic

# Get node and install mjml for email templates
ARG NODE_VERSION=v24.6.0
ARG MJML_VERSION=4.17.1
RUN curl -fsSL https://nodejs.org/dist/${NODE_VERSION}/node-${NODE_VERSION}-linux-x64.tar.xz -o node.tar.xz \
    && tar -xf node.tar.xz -C /usr/local --strip-components=1 \
    && rm node.tar.xz
ENV PATH="/usr/local/bin:${PATH}"
RUN npm install -g mjml@${MJML_VERSION}

# Add timestamp
RUN date +"%d.%m.%y %T" > timestamp

RUN pip --timeout=1000 install --no-dependencies -r requirements.txt

ENTRYPOINT ["/badgr_server/entrypoint.dev.sh"]
