# Generated by Django 5.2.8 on 2026-02-09 15:35

import mainsite.models
import uuid
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0026_iframeurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='altchachallenge',
            name='id',
            field=mainsite.models.Char32UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='iframeurl',
            name='id',
            field=mainsite.models.Char32UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
